### ISSUE TITLE
esm-seedrandom incompatible to jest (unit testing hard)

### ISSUE THREAD

**Issue by kurellajunior** [shanewholloway/js-esm-seedrandom#2]
When running jest based tests via npm with a js file that imports esm-seedrandom it fails hard:
```
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /home/kurella/MIA/git/mia-coder/node_modules/esm-seedrandom/esm/index.mjs:565
    export { prng_alea, prng_arc4, prng_tychei, prng_xor128, prng_xor4096, prng_xorshift7, prng_xorwow };
    ^^^^^^

    SyntaxError: Unexpected token 'export'

      1 | import { LoremIpsum } from "lorem-ipsum";
    > 2 | import { prng_alea } from "esm-seedrandom";
        | ^
      3 | import { generateArray } from "@/random";
      4 |
      5 | const alpha = "abcdefghijklmnopqrstuvwxyz";

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at Object.<anonymous> (src/stories/seedRandom.ts:2:1)

``` 
Any idea, how to fix or at least elegantly bypass this?

**Comment by shanewholloway** [comment]
This issue looks related to ESM module imports versus CommonJS `require()` statements. 

My apologies, I'm discovering this issue after three plus years. I'm going to close this as overcome-by-events; please reopen if you're still encountering problems.
